
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    token: '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'
  };
